### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by The-Daishogun** [alimaktabi/quera-frontend-task#1]
According to [yarn documentation](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored) ./yarn/cache/* folder should not be committed to the repo

consider adding the folders mentioned in the documentation to your .gitignore file

**Comment by Bob-six** [comment]
It should be fixed by now

**Comment by The-Daishogun** [comment]
Thanks for the fix
